UniversityManagementSystem/UniversityManagementSystem/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class CoursesController : Controller
    {
        
        public IActionResult Index()
        {
            return View();
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Controllers/GroupController.cs
using ApplicationCore.DTO;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class GroupController : Controller
    {
        private readonly IGroupService _groupService;

        public GroupController(IGroupService groupService)
        {
            _groupService = groupService;
        }

        public IActionResult Index(Guid courseId, Guid? groupId = null)
        {
            var groups = _groupService.GetCourseGroups(courseId);
            ViewBag.courseId = courseId;
            ViewBag.groupId = groupId;

            return View(groups);
        }

        public IActionResult GetStudents(Guid groupId, Guid courseId)
        {
            var students = _groupService.GetStudentsByGroup(groupId);

            ViewBag.CourseId = courseId;

            return PartialView("_StudentTable", students); 
        }

        public IActionResult Create(Guid courseId)
        {
            var groupDto = new GroupDto
            {
                CourseId = courseId
            };

            return View(groupDto);
        }

        [HttpPost]
        public IActionResult Create(GroupDto groupDto)
        {
            if(!ModelState.IsValid)
            {
                return View(groupDto);
            }

            _groupService.GetOrCreate(groupDto.Name, groupDto.CourseId);

            TempData["SuccessMessage"] = $"The group {groupDto.Name} has been successfully created!";

            return RedirectToAction("Index", "Group", new { groupDto.CourseId });
        }

        public IActionResult Edit(Guid courseId, Guid groupId)
        {
            var group = _groupService.GetGroupById(groupId);

            var groupDto = new GroupDto
            {
                CourseId = courseId,
                GroupId = groupId,
                Name = group.Name
            };
            
            return View(groupDto);
        }

        [HttpPost]
        public IActionResult Edit(GroupDto groupDto)
        {
            _groupService.UpdateGroup(groupDto.GroupId, groupDto.Name);

            return RedirectToAction("Index", "Group", new { groupDto.CourseId, groupDto.GroupId });
        }

        public IActionResult Delete(Guid courseId, Guid groupId)
        {
            try
            {
                _groupService.DeleteGroup(groupId);
            }
            catch (InvalidOperationException ex)
            {
                TempData["ErrorMessage"] = ex.Message;

                return RedirectToAction("Index", "Group", new { courseId });
            }

            return RedirectToAction("Index", "Group", new { courseId });
        }
    }
}
    

UniversityManagementSystem/UniversityManagementSystem/Controllers/HomeController.cs
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace UniversityManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly ICourseService _courseService;

        public HomeController(ILogger<HomeController> logger, ICourseService courseService)
        {
            _logger = logger;
            _courseService = courseService;
        }

        public IActionResult Index()
        {
            var courses = _courseService.GetAllCourses();

            return View(courses);
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Controllers/NotificationsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class NotificationsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class ProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Controllers/ScheduleController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class ScheduleController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class SettingsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Controllers/StudentController.cs
using ApplicationCore.DTO;
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;

        public StudentController(IStudentService studentService)
        {
            _studentService = studentService;
        }

        public IActionResult Create(Guid courseId, Guid groupId)
        {
            var studentDto = new StudentDto
            {
                CourseId = courseId,
                GroupId = groupId
            };

            return View(studentDto);
        }

        [HttpPost]
        public IActionResult Create(StudentDto studentDto)
        {
            if(!ModelState.IsValid)
            {
                return View(studentDto);
            }

            _studentService.GetOrCreate(studentDto.FirstName, studentDto.LastName, studentDto.GroupId);

            TempData["SuccessMessage"] = $"The student {studentDto.FirstName} {studentDto.LastName} has been successfully created!";

            return RedirectToAction("Index", "Group", new { studentDto.CourseId, studentDto.GroupId });
        }

        public IActionResult Edit(Guid courseId, Guid groupId, Guid studentId)
        {
            var student = _studentService.GetStudentById(studentId);

            var studentDto = new StudentDto
            {
                CourseId = courseId,
                GroupId = groupId,
                StudentId = studentId,
                FirstName = student.FirstName,
                LastName = student.LastName
            };

            return View(studentDto);
        }

        [HttpPost]
        public IActionResult Edit(StudentDto studentDto)
        {
            _studentService.UpdateStudent(studentDto.StudentId, studentDto.FirstName, studentDto.LastName);

            return RedirectToAction("Index", "Group", new { studentDto.CourseId, studentDto.GroupId });
        }

        public IActionResult Delete(Guid courseId, Guid groupId, Guid studentId)
        {
            _studentService.DeleteStudent(studentId);

            return RedirectToAction("Index", "Group", new { courseId, groupId });
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class TeacherController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

UniversityManagementSystem/UniversityManagementSystem/Views/Group/Create.cshtml
@using ApplicationCore.DTO;

@model GroupDto

<!DOCTYPE html>
<html>
<head>
    <link href="/css/form-styles.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h2>Create Group</h2>
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label for="Name">Name</label>
                <input type="text" id="Name" name="Name">
            </div>
            <div class="btn-container">
                <a asp-controller="Group" asp-action="Index" asp-route-courseId="@Model.CourseId" class="btn btn-cancel">Cancel</a>
                <button type="submit" class="btn btn-add">Submit</button>
            </div>
        </form>
    </div>
</body>
</html>

UniversityManagementSystem/UniversityManagementSystem/Views/Group/Index.cshtml
@using ApplicationCore.Entities
@using System.Collections.ObjectModel

@model ObservableCollection<Group>

@{
	var courseId = ViewBag.courseId;
	var groupId = ViewBag.GroupId as Guid?;
	string tableHeight = "700px"; 
}

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Group Page</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
	integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" href="~/css/style.css">
</head>

<body>
	<div class="wrapper">
		<aside id="sidebar" class="expand">
			<div class="d-flex">
				<button class="toggle-btn" type="button">
					<img class="sidebar-logo-img" src="/images/grid.png" />
				</button>
				<div class="sidebar-logo">
					<label>University</label>
				</div>
			</div>
			<ul class="sidebar-nav">
				<li class="sidebar-item">
					<a asp-controller="Home" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/home.png" />
						<span>Home</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Teacher" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/teachers.png" />
						<span>Teachers</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Schedule" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/sсhedule.png" />
						<span>Schedule</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Notifications" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/notifications.png" />
						<span>Notifications</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Settings" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/settings.png" />
						<span>Settings</span>
					</a>
				</li>
			</ul>
			<div class="sidebar-footer">
				<a href="#" class="sidebar-link">
					<img class="sidebar-logo-img" src="/images/exit.png" />
					<span>Logout</span>
				</a>
			</div>
		</aside>
		<div class="main">
			<nav class="navbar navbar-expand mb-5">
				<form action="#" class="d-none d-sm-inline-block"></form>
				<div class="navbar-collapse collapse">
					<ul class="navbar-nav ms-auto px-3">
						<li class="nav-item dropdown">
							<a asp-controller="Profile" asp-action="Index" class="nav-icon pe-md-0">
								<img src="/images/user.png" class="avatar img-fluid" alt="">
							</a>
						</li>
					</ul>
				</div>
			</nav>
			<main class="content px-5">

				@if (TempData["SuccessMessage"] != null)
				{
					<div class="alert alert-success">@TempData["SuccessMessage"]</div>
					tableHeight = "625px";
				}

				@if (TempData["ErrorMessage"] != null)
				{
					<div class="alert alert-danger">@TempData["ErrorMessage"]</div>
					tableHeight = "625px";
				}

				<div class="mb-2">
					<h2>List of groups</h2>
					<input type="hidden" id="courseId" name="courseId" value="@courseId" />
					<input type="hidden" id="groupId" name="groupId" value="@groupId" />
					<input type="hidden" id="selectedGroupId" name="groupId" />
				</div>
				<div class="d-flex align-items-center mb-3">
					<h5>Number of group @Model.Count</h5>
					<h5 class="me-2 px-2" style="margin-left: 80px;">Add new</h5>
					<a class="btn btn-primary position-relative rounded-circle p-0 d-flex align-items-center justify-content-center"
					   style="width: 42px; height: 42px; background-color: #0a2a66; position: relative; top: -5px; border: none;" asp-controller="Group" asp-action="Create" asp-route-courseId="@courseId">
						<img src="/images/plus.png" alt="Icon" style="width: 60%; height: 60%;">
					</a>
					<h5 class="me-2 px-2" style="margin-left: 545px; margin-right:260px"><strong>Students</strong></h5>
					<div class="ms-auto d-flex align-items-center">
						<h5 class="me-2 px-2">Add new</h5>
						<a id="add-student-btn" class="btn btn-primary position-relative rounded-circle p-0 d-flex align-items-center justify-content-center"
						   style="width: 42px; height: 42px; background-color: #0a2a66; border: none; position: relative; top: -5px;">
							<img src="/images/plus.png" alt="Icon" style="width: 60%; height: 60%;">
						</a>
					</div>
				</div>

				<div class="tables-container d-flex">
					<div class="scroll-tableg me-3" style="@($"height: {tableHeight};")">
						<table class="table-stripeds" style="width: 420px;">
							<thead>
								<tr>
									<th>Name</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								@foreach (var group in Model)
								{
									<tr>
										<td>
											<a href="#" class="group-link" data-group-id="@group.GroupId" style="display: block; text-decoration: none; color: inherit; padding: 10px;">
												@group.Name
											</a>
										</td>
										<td>
											<a class="btn action-btne" asp-controller="Group" asp-action="Edit" asp-route-courseId="@courseId" asp-route-groupId="@group.GroupId">
												<img src="/images/edit-box.png" />
											</a>
											<a class="btn action-btnd" asp-controller="Group" asp-action="Delete" asp-route-courseId="@courseId" asp-route-groupId="@group.GroupId" onclick="return confirm('Would you like to confirm your choice ?')">
												<img src="/images/delete.png" />
											</a>
										</td>
									</tr>
								}
							</tbody>
						</table>
					</div>
					<div class="scroll-tables">
						<div id="students-container">
							@if (groupId == null)
							{
								<table class="table-striped">
									<thead>
										<tr>
											<th></th>
											<th>First Name</th>
											<th>Last Name</th>
											<th></th>
										</tr>
									</thead>
									<tbody>
									</tbody>
								</table>
							}
							else
							{
								var group = @Model.FirstOrDefault(g => g.GroupId == groupId);

								<table class="table-striped">
									<thead>
										<tr>
											<th></th>
											<th>First Name</th>
											<th>Last Name</th>
											<th></th>
										</tr>
									</thead>
									<tbody>
										@foreach (var student in group.Students)
										{
											<tr>
												<td><img src="/images/student.png" style="height: 40px; width: 40px" /></td>
												<td>@student.FirstName</td>
												<td>@student.LastName</td>
												<td>
													<a class="btn action-btne" asp-controller="Student" asp-action="Edit" asp-route-courseId="@courseId" asp-route-groupId="@student.GroupId" asp-route-studentId="@student.StudentId">
														<img src="/images/edit-box.png" />
													</a>
													<a class="btn action-btnd" asp-controller="Student" asp-action="Delete" asp-route-courseId="@courseId" asp-route-groupId="@student.GroupId" asp-route-studentId="@student.StudentId" onclick="return confirm('Would you like to confirm your choice ?')">
														<img src="/images/delete.png" />
													</a>
												</td>
											</tr>
										}
									</tbody>
								</table>
							}
						</div>
					</div>
				</div>
			</main>
		</div>
	</div>
	<script src="~/js/script.js"></script>
</body>
</html>

UniversityManagementSystem/UniversityManagementSystem/Views/Group/_StudentTable.cshtml
@using ApplicationCore.Entities;
@using System.Collections.ObjectModel;

@model ObservableCollection<Student>

@{
	var courseId = ViewBag.CourseId;
}

<table class="table-striped">
	<thead>
		<tr>
			<th></th>
			<th>First Name</th>
			<th>Last Name</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var student in Model)
		{
			<tr>
				<td><img src="/images/student.png" style="height: 40px; width: 40px" /></td>
				<td>@student.FirstName</td>
				<td>@student.LastName</td>
				<td>
					<a class="btn action-btne" asp-controller="Student" asp-action="Edit" asp-route-courseId="@courseId" asp-route-groupId="@student.GroupId" asp-route-studentId="@student.StudentId">
						<img src="/images/edit-box.png" />
					</a>
					<a class="btn action-btnd" asp-controller="Student" asp-action="Delete" asp-route-courseId="@courseId" asp-route-groupId="@student.GroupId" asp-route-studentId="@student.StudentId" onclick="return confirm('Would you like to confirm your choice ?')">
						<img src="/images/delete.png" />
					</a>
				</td>
			</tr>
		}
	</tbody>
</table>

UniversityManagementSystem/UniversityManagementSystem/Views/Home/Index.cshtml
@using ApplicationCore.Entities
@using System.Collections.ObjectModel

@model ObservableCollection<Course>
@{

}

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Home Page</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
		  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" href="~/css/style.css">
</head>

<body>
	<div class="wrapper">
		<aside id="sidebar" class="expand">
			<div class="d-flex">
				<button class="toggle-btn" type="button">
					<img class="sidebar-logo-img" src="/images/grid.png" />
				</button>
				<div class="sidebar-logo">
					<label>University</label>
				</div>
			</div>
			<ul class="sidebar-nav">
				<li class="sidebar-item">
					<a asp-controller="Home" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/home.png" />
						<span>Home</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Teacher" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/teachers.png" />
						<span>Teachers</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Schedule" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/sсhedule.png" />
						<span>Schedule</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Notifications" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/notifications.png" />
						<span>Notifications</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Settings" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/settings.png" />
						<span>Settings</span>
					</a>
				</li>
			</ul>
			<div class="sidebar-footer">
				<a href="#" class="sidebar-link">
					<img class="sidebar-logo-img" src="/images/exit.png" />
					<span>Logout</span>
				</a>
			</div>
		</aside>
		<div class="main">
			<nav class="navbar navbar-expand mb-5">
				<form action="#" class="d-none d-sm-inline-block"></form>
				<div class="navbar-collapse collapse">
					<ul class="navbar-nav ms-auto px-3">
						<li class="nav-item dropdown">
							<a asp-controller="Profile" asp-action="Index" class="nav-icon pe-md-0">
								<img src="/images/user.png" class="avatar img-fluid" alt="">
							</a>
						</li>
					</ul>
				</div>
			</nav>
			<main class="content px-5">
				<div class="mb-2">
					<h2>List of courses</h2>
				</div>
				<div class="d-flex justify-content-between align-items-center mb-3">
					<h5>Number of course @Model.Count</h5>
					<div class="d-flex align-items-center">
						<h5 class="me-2 px-2">Add new</h5>
						<button class="btn btn-primary position-relative rounded-circle p-0 d-flex align-items-center justify-content-center"
								style="width: 42px; height: 42px; background-color: #0a2a66; top: -6px; border: none;">
							<img src="/images/plus.png" alt="Icon" style="width: 60%; height: 60%;">
						</button>
					</div>
				</div>
				<div class="scroll-table">
					<table class="table-striped">
						<thead>
							<tr>
								<th>Name</th>
								<th>Description</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<tr>
							</tr>
							@foreach (var course in Model)
							{
								<tr>
									<td>
										<a asp-controller="Group" asp-action="Index" asp-route-courseId="@course.CourseId" style="display: block; text-decoration: none; color: inherit; padding: 10px;">
											@course.Name
										</a>
									</td>

									<td>
										<a asp-controller="Group" asp-action="Index" asp-route-courseId="@course.CourseId" style="display: block; text-decoration: none; color: inherit; padding: 10px;">
											@course.Description
										</a>
									</td>

									<td>
										<a class="btn action-btne">
											<img src="/images/edit-box.png" />
										</a>
										<a class="btn action-btnd">
											<img src="/images/delete.png" />
										</a>
									</td>
								</tr>
							}
						</tbody>
					</table>
				</div>
			</main>
		</div>
	</div>
	<script src="~/js/script.js"></script>
</body>
</html>

UniversityManagementSystem/UniversityManagementSystem/Views/Notifications/Index.cshtml
@using ApplicationCore.Entities
@using System.Collections.ObjectModel

@{

}

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Notifications Page</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
		  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" href="~/css/style.css">
</head>

<body>
	<div class="wrapper">
		<aside id="sidebar" class="expand">
			<div class="d-flex">
				<button class="toggle-btn" type="button">
					<img class="sidebar-logo-img" src="/images/grid.png" />
				</button>
				<div class="sidebar-logo">
					<label>University</label>
				</div>
			</div>
			<ul class="sidebar-nav">
				<li class="sidebar-item">
					<a asp-controller="Home" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/home.png" />
						<span>Home</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Teacher" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/teachers.png" />
						<span>Teachers</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Schedule" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/sсhedule.png" />
						<span>Schedule</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Notifications" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/notifications.png" />
						<span>Notifications</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Settings" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/settings.png" />
						<span>Settings</span>
					</a>
				</li>
			</ul>
			<div class="sidebar-footer">
				<a href="#" class="sidebar-link">
					<img class="sidebar-logo-img" src="/images/exit.png" />
					<span>Logout</span>
				</a>
			</div>
		</aside>
		<div class="main">
			<nav class="navbar navbar-expand mb-5">
				<form action="#" class="d-none d-sm-inline-block"></form>
				<div class="navbar-collapse collapse">
					<ul class="navbar-nav ms-auto px-3">
						<li class="nav-item dropdown">
							<a asp-controller="Profile" asp-action="Index" class="nav-icon pe-md-0">
								<img src="/images/user.png" class="avatar img-fluid" alt="">
							</a>
						</li>
					</ul>
				</div>
			</nav>
			<main class="content px-5">
				<div class="text-center" style="font-size: 24px; font-weight: bold; color: #555;">
					<img src="/images/notificationsd.gif" style="width: 200px; height: 200px; margin-top: 150px" />
					<p>The Notifications page is in development</p>
				</div>
			</main>

		</div>
	</div>
	<script src="~/js/script.js"></script>
</body>
</html>

UniversityManagementSystem/UniversityManagementSystem/Views/Schedule/Index.cshtml
@using ApplicationCore.Entities
@using System.Collections.ObjectModel

@{

}

<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Schedule Page</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
		  integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
	<link rel="stylesheet" href="~/css/style.css">
</head>

<body>
	<div class="wrapper">
		<aside id="sidebar" class="expand">
			<div class="d-flex">
				<button class="toggle-btn" type="button">
					<img class="sidebar-logo-img" src="/images/grid.png" />
				</button>
				<div class="sidebar-logo">
					<label>University</label>
				</div>
			</div>
			<ul class="sidebar-nav">
				<li class="sidebar-item">
					<a asp-controller="Home" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/home.png" />
						<span>Home</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Teacher" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/teachers.png" />
						<span>Teachers</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Schedule" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/sсhedule.png" />
						<span>Schedule</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Notifications" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/notifications.png" />
						<span>Notifications</span>
					</a>
				</li>
				<li class="sidebar-item">
					<a asp-controller="Settings" asp-action="Index" class="sidebar-link">
						<img class="sidebar-logo-img" src="/images/settings.png" />
						<span>Settings</span>
					</a>
				</li>
			</ul>
			<div class="sidebar-footer">
				<a href="#" class="sidebar-link">
					<img class="sidebar-logo-img" src="/images/exit.png" />
					<span>Logout</span>
				</a>
			</div>
		</aside>
		<div class="main">
			<nav class="navbar navbar-expand mb-5">
				<form action="#" class="d-none d-sm-inline-block"></form>
				<div class="navbar-collapse collapse">
					<ul class="navbar-nav ms-auto px-3">
						<li class="nav-item dropdown">
							<a asp-controller="Profile" asp-action="Index" class="nav-icon pe-md-0">
								<img src="/images/user.png" class="avatar img-fluid" alt="">
							</a>
						</li>
					</ul>
				</div>
			</nav>
			<main class="content px-5">
				<div class="text-center" style="font-size: 24px; font-weight: bold; color: #555;">
					<img src="/images/schedule.gif" style="width: 200px; height: 200px; margin-top: 150px" />
					<p>The Schedule page is in development</p>
				</div>
			</main>

		</div>
	</div>
	<script src="~/js/script.js"></script>
</body>
</html>